name: Python App CI/CD Pipeline with Direct Deployment

on:
  workflow_dispatch:  # 👈 This adds the manual trigger option
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: |
        pip install -r requirements.txt

    # Run tests (Placeholder for actual tests)
    - name: Run tests
      run: |
        echo "Run tests"

    # Azure Login using GitHub Secrets
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Debug secrets
      run: |
        echo "RG: ${{ secrets.RESOURCE_GROUP }}"
        echo "VMSS: ${{ secrets.VMSS_NAME }}"


    # Remove old extension (optional cleanup step)
    - name: Remove old CustomScript Extension
      run: |
        az vm extension delete \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --vm-name ${{ secrets.VM_NAME }} \
          --name CustomScript || true


    - name: Deploy to Azure VMSS
      run: |
        az vmss extension set \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --vmss-name ${{ secrets.VMSS_NAME }} \
          --name CustomScript \
          --force-update \
          --publisher Microsoft.Azure.Extensions \
          --version 2.1 \
          --settings '{"commandToExecute": "bash /home/azureuser/stage65/update.sh"}'

    
